#!/bin/sh

: ${ZIP:=zip}
ZIPARCHIVE=scion-0.1.0.8.zip

rm -f ${ZIPARCHIVE}

find docs emacs lib README.markdown scion.cabal server Setup.hs vim_runtime_path \
	'!' -name '*~' '!' -name '*.swp' -print | \
	"${ZIP}" ${ZIPARCHIVE} -@
